In [1]:
pip install pandas pyreadstat

Requirement already satisfied: pandas in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (2.1.2)
Requirement already satisfied: pyreadstat in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (1.2.8)
Requirement already satisfied: numpy<2,>=1.26.0 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from pandas) (1.26.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~ip (c:\Users\hp\AppData\Local\Programs\Python\Python312\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (c:\Users\hp\AppData\Local\Programs\Python\Python312\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (c:\Users\hp\AppData\Local\Programs\Python\Python312\Lib\site-packages)

In [2]:
pip install stata_kernel

Requirement already satisfied: stata_kernel in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (1.12.2)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: beautifulsoup4>=4.6.3 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from stata_kernel) (4.12.2)
Requirement already satisfied: jupyter_client>=5.2.3 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from stata_kernel) (8.5.0)
Requirement already satisfied: IPython>=6.5.0 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from stata_kernel) (8.16.1)
Requirement already satisfied: ipykernel>=4.8.2 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from stata_kernel) (6.26.0)
Requirement already satisfied: pandas>=0.22.0 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from stata_kernel) (2.1.2)
Requirement already satisfied: packaging>=17.1 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from stata_kernel) (23.2)
Requirement already satisfied: pillow>=5.2.0 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from stata_kernel) (10.1.0)
Requirement already satisfied: pexpect>=4.6.0 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from stata_kernel) (4.9.0)
Requirement already satisfied: pygments>=2.2.0 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from stata_kernel) (2.16.1)
Requirement already satisfied: pywin32>=223 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from stata_kernel) (306)
Requirement already satisfied: requests>=2.19.1 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from stata_kernel) (2.32.3)
Requirement already satisfied: soupsieve>1.2 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from beautifulsoup4>=4.6.3->stata_kernel) (2.5)
Requirement already satisfied: comm>=0.1.1 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from ipykernel>=4.8.2->stata_kernel) (0.1.4)
Requirement already satisfied: debugpy>=1.6.5 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from ipykernel>=4.8.2->stata_kernel) (1.8.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from ipykernel>=4.8.2->stata_kernel) (5.4.0)
Requirement already satisfied: matplotlib-inline>=0.1 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from ipykernel>=4.8.2->stata_kernel) (0.1.6)
Requirement already satisfied: nest-asyncio in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from ipykernel>=4.8.2->stata_kernel) (1.5.8)
Requirement already satisfied: psutil in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from ipykernel>=4.8.2->stata_kernel) (5.9.6)
Requirement already satisfied: pyzmq>=20 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from ipykernel>=4.8.2->stata_kernel) (25.1.1)
Requirement already satisfied: tornado>=6.1 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from ipykernel>=4.8.2->stata_kernel) (6.3.3)
Requirement already satisfied: traitlets>=5.4.0 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from ipykernel>=4.8.2->stata_kernel) (5.12.0)
Requirement already satisfied: backcall in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from IPython>=6.5.0->stata_kernel) (0.2.0)
Requirement already satisfied: decorator in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from IPython>=6.5.0->stata_kernel) (5.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from IPython>=6.5.0->stata_kernel) (0.19.1)
Requirement already satisfied: pickleshare in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from IPython>=6.5.0->stata_kernel) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from IPython>=6.5.0->stata_kernel) (3.0.39)
Requirement already satisfied: stack-data in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from IPython>=6.5.0->stata_kernel) (0.6.3)
Requirement already satisfied: colorama in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from IPython>=6.5.0->stata_kernel) (0.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from jupyter_client>=5.2.3->stata_kernel) (2.8.2)
Requirement already satisfied: numpy<2,>=1.26.0 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from pandas>=0.22.0->stata_kernel) (1.26.1)
Requirement already satisfied: pytz>=2020.1 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from pandas>=0.22.0->stata_kernel) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from pandas>=0.22.0->stata_kernel) (2023.3)
Requirement already satisfied: ptyprocess>=0.5 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from pexpect>=4.6.0->stata_kernel) (0.7.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from requests>=2.19.1->stata_kernel) (3.3.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from requests>=2.19.1->stata_kernel) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from requests>=2.19.1->stata_kernel) (2.2.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from requests>=2.19.1->stata_kernel) (2023.7.22)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from jedi>=0.16->IPython>=6.5.0->stata_kernel) (0.8.3)
Requirement already satisfied: platformdirs>=2.5 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel>=4.8.2->stata_kernel) (3.11.0)
Requirement already satisfied: wcwidth in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30->IPython>=6.5.0->stata_kernel) (0.2.8)
Requirement already satisfied: six>=1.5 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.8.2->jupyter_client>=5.2.3->stata_kernel) (1.16.0)
Requirement already satisfied: executing>=1.2.0 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from stack-data->IPython>=6.5.0->stata_kernel) (2.0.0)
Requirement already satisfied: asttokens>=2.1.0 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from stack-data->IPython>=6.5.0->stata_kernel) (2.4.1)
Requirement already satisfied: pure-eval in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from stack-data->IPython>=6.5.0->stata_kernel) (0.2.2)

WARNING: Ignoring invalid distribution ~ip (c:\Users\hp\AppData\Local\Programs\Python\Python312\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (c:\Users\hp\AppData\Local\Programs\Python\Python312\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (c:\Users\hp\AppData\Local\Programs\Python\Python312\Lib\site-packages)

In [3]:
import pandas as pd

df_pollution = pd.read_stata("datasets/pollution/panel20200321.dta")
df_pollution

,stationcode,pollutant,date,proven,provorg,data,year,month,day,edate,time
0,1001A,AQI,20180125,nonNeighbor,Beijing,24.727272,2018.0,1.0,25.0,2018-01-25,-21.0
1,1002A,AQI,20180125,nonNeighbor,Beijing,30.583334,2018.0,1.0,25.0,2018-01-25,-21.0
2,1003A,AQI,20180125,nonNeighbor,Beijing,21.416666,2018.0,1.0,25.0,2018-01-25,-21.0
3,1004A,AQI,20180125,nonNeighbor,Beijing,23.416666,2018.0,1.0,25.0,2018-01-25,-21.0
4,1005A,AQI,20180125,nonNeighbor,Beijing,25.625000,2018.0,1.0,25.0,2018-01-25,-21.0
...,...,...,...,...,...,...,...,...,...,...,...
1685049,3180A,SO2,20200221,nonNeighbor,Yunnan,4.000000,2020.0,2.0,21.0,2020-02-21,28.0
1685050,3182A,SO2,20200221,nonNeighbor,Sichuan,1.500000,2020.0,2.0,21.0,2020-02-21,28.0
1685051,3183A,SO2,20200221,nonNeighbor,Sichuan,3.625000,2020.0,2.0,21.0,2020-02-21,28.0
1685052,3184A,SO2,20200221,nonNeighbor,Heilongjiang,NaN,2020.0,2.0,21.0,2020-02-21,28.0
1685053,3185A,SO2,20200221,nonNeighbor,Shanxi,8.750000,2020.0,2.0,21.0,2020-02-21,28.0

In [4]:
df_firm = pd.read_stata("datasets/CEMS/allair_firmLNY_balanced.dta")
df_firm

,firm_name,pollutant,edate,time,concentration,provorg,dow,proven
0,安徽郎溪南方水泥有限公司,Particle,21572.0,-12.0,7.762000,Anhui,3.0,HubeiNeighbor
1,安徽郎溪南方水泥有限公司,Particle,21573.0,-11.0,7.439913,Anhui,4.0,HubeiNeighbor
2,安徽郎溪南方水泥有限公司,Particle,21574.0,-10.0,7.495250,Anhui,5.0,HubeiNeighbor
3,安徽郎溪南方水泥有限公司,Particle,21575.0,-9.0,7.600667,Anhui,6.0,HubeiNeighbor
4,安徽郎溪南方水泥有限公司,Particle,21576.0,-8.0,7.589958,Anhui,0.0,HubeiNeighbor
...,...,...,...,...,...,...,...,...
187950,龙游县金怡热电有限公司,Particle,21962.0,24.0,0.695833,Zhejiang,1.0,nonNeighbor
187951,龙游县金怡热电有限公司,Particle,21963.0,25.0,0.729167,Zhejiang,2.0,nonNeighbor
187952,龙游县金怡热电有限公司,Particle,21964.0,26.0,0.745833,Zhejiang,3.0,nonNeighbor
187953,龙游县金怡热电有限公司,Particle,21965.0,27.0,0.887500,Zhejiang,4.0,nonNeighbor
187954,龙游县金怡热电有限公司,Particle,21966.0,28.0,0.900000,Zhejiang,5.0,nonNeighbor

In [5]:
df_firmNOX = pd.read_stata("datasets/CEMS/NOXnfirms.dta")
df_firmNOX

,time,year,provorg,edate,nfirms,pollutant,dow,proven,provid
0,-21.0,2019.0,Anhui,21563.0,8,NOX,1.0,HubeiNeighbor,1.0
1,-20.0,2019.0,Anhui,21564.0,13,NOX,2.0,HubeiNeighbor,1.0
2,-19.0,2019.0,Anhui,21565.0,13,NOX,3.0,HubeiNeighbor,1.0
3,-18.0,2019.0,Anhui,21566.0,13,NOX,4.0,HubeiNeighbor,1.0
4,-17.0,2019.0,Anhui,21567.0,13,NOX,5.0,HubeiNeighbor,1.0
...,...,...,...,...,...,...,...,...,...
1095,24.0,2020.0,Zhejiang,21962.0,295,NOX,1.0,nonNeighbor,11.0
1096,25.0,2020.0,Zhejiang,21963.0,299,NOX,2.0,nonNeighbor,11.0
1097,26.0,2020.0,Zhejiang,21964.0,299,NOX,3.0,nonNeighbor,11.0
1098,27.0,2020.0,Zhejiang,21965.0,313,NOX,4.0,nonNeighbor,11.0
1099,28.0,2020.0,Zhejiang,21966.0,318,NOX,5.0,nonNeighbor,11.0

In [6]:
df_firmNOX = pd.read_stata("datasets/CEMS/allair_firmLNY_balanced.dta")
df_firmNOX

,firm_name,pollutant,edate,time,concentration,provorg,dow,proven
0,安徽郎溪南方水泥有限公司,Particle,21572.0,-12.0,7.762000,Anhui,3.0,HubeiNeighbor
1,安徽郎溪南方水泥有限公司,Particle,21573.0,-11.0,7.439913,Anhui,4.0,HubeiNeighbor
2,安徽郎溪南方水泥有限公司,Particle,21574.0,-10.0,7.495250,Anhui,5.0,HubeiNeighbor
3,安徽郎溪南方水泥有限公司,Particle,21575.0,-9.0,7.600667,Anhui,6.0,HubeiNeighbor
4,安徽郎溪南方水泥有限公司,Particle,21576.0,-8.0,7.589958,Anhui,0.0,HubeiNeighbor
...,...,...,...,...,...,...,...,...
187950,龙游县金怡热电有限公司,Particle,21962.0,24.0,0.695833,Zhejiang,1.0,nonNeighbor
187951,龙游县金怡热电有限公司,Particle,21963.0,25.0,0.729167,Zhejiang,2.0,nonNeighbor
187952,龙游县金怡热电有限公司,Particle,21964.0,26.0,0.745833,Zhejiang,3.0,nonNeighbor
187953,龙游县金怡热电有限公司,Particle,21965.0,27.0,0.887500,Zhejiang,4.0,nonNeighbor
187954,龙游县金怡热电有限公司,Particle,21966.0,28.0,0.900000,Zhejiang,5.0,nonNeighbor

In [7]:
df_firmSO2 = pd.read_stata("datasets/CEMS/SO2nfirms.dta")
df_firmSO2

,time,year,provorg,edate,nfirms,pollutant,dow,proven,provid
0,-21.0,2019.0,Anhui,21563.0,12,SO2,1.0,HubeiNeighbor,1.0
1,-20.0,2019.0,Anhui,21564.0,17,SO2,2.0,HubeiNeighbor,1.0
2,-19.0,2019.0,Anhui,21565.0,17,SO2,3.0,HubeiNeighbor,1.0
3,-18.0,2019.0,Anhui,21566.0,18,SO2,4.0,HubeiNeighbor,1.0
4,-17.0,2019.0,Anhui,21567.0,19,SO2,5.0,HubeiNeighbor,1.0
...,...,...,...,...,...,...,...,...,...
1095,24.0,2020.0,Zhejiang,21962.0,287,SO2,1.0,nonNeighbor,11.0
1096,25.0,2020.0,Zhejiang,21963.0,299,SO2,2.0,nonNeighbor,11.0
1097,26.0,2020.0,Zhejiang,21964.0,299,SO2,3.0,nonNeighbor,11.0
1098,27.0,2020.0,Zhejiang,21965.0,308,SO2,4.0,nonNeighbor,11.0
1099,28.0,2020.0,Zhejiang,21966.0,316,SO2,5.0,nonNeighbor,11.0

In [8]:
df_weather = pd.read_stata("datasets/weather/provmon.dta")
df_weather

     year  month    provorg       temp      wdsp      prcp      visib
0    2018      1      Anhui   0.824629  2.998476  0.912373   6.900138
1    2018      1    Beijing  -3.793907  3.772039  0.000000   7.644365
2    2018      1  Chongqing   5.387993  1.963601  0.148831   7.269285
3    2018      1     Fujian  10.143369  2.502800  0.514713  12.811558
4    2018      1      Gansu  -8.317316  2.856416  0.157827  18.892597
..    ...    ...        ...        ...       ...       ...        ...
274  2020      3    Tianjin   8.266666  3.894345  0.034834  13.450059
275  2020      3      Tibet  -0.062302  3.085381  0.040368  28.456005
276  2020      3   Xinjiang   3.341487  2.263307  0.216383  17.263027
277  2020      3     Yunnan  16.827604  2.610517  0.031608  21.447884
278  2020      3   Zhejiang  12.272980  2.928826  0.273352  12.035668

[279 rows x 7 columns]

In [9]:
with open("do files/Figures/Figure 1.do", "r") as file:
    stata_code = file.read()

print(stata_code[:500])

set more off

use panel20200321.dta, clear

collapse (mean) data, by(pollutant date proven)
gen year = floor(date/10000)
gen month = floor((date - year*10000)/100)
gen day = date - year*10000 - month*100
gen edate = mdy(month,day,year)
format edate %td
replace pollutant="PM25" if pollutant=="PM2.5"

gen time=.
replace time= edate - mdy(1,24,2020) if year==2020
replace time= edate - mdy(2,4,2019) if year==2019
replace time= edate - mdy(2,15,2018) if year==2018



preserve
keep if pollutant=="SO2"

**PREPROCESSING FOR AMBIENT AIR QUALITY DATASET**

In [10]:
import pandas as pd
import numpy as np
from scipy.spatial import cKDTree

In [11]:
pollution = pd.read_stata("datasets/pollution/panel20200321.dta")
weather = pd.read_stata("datasets/weather/provmon.dta")

In [12]:
pollution.columns = pollution.columns.str.lower().str.replace(" ", "_")

In [13]:
pollution["date"] = pd.to_datetime(pollution["date"], format="%Y%m%d")

In [14]:
pollution.drop(columns=["edate", "time", "year", "month", "day"], inplace=True)

In [15]:
print(pollution.isnull().sum())

stationcode         0
pollutant           0
date                0
proven              0
provorg             0
data           152660
dtype: int64

In [16]:
pollution["data"].fillna(method="ffill", inplace=True)
# Fill missing pollution data using forward-fill (ffill) since pollution data is time-dependent.

C:\Users\hp\AppData\Local\Temp\ipykernel_22984\2317289107.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  pollution["data"].fillna(method="ffill", inplace=True)

In [17]:
pollution_daily = pollution.groupby(["date", "provorg"])["data"].mean().reset_index()
pollution_daily.rename(columns={"data": "avg_aqi"}, inplace=True)

**Weather Preprocessing**

In [18]:
weather.columns = weather.columns.str.lower().str.replace(" ", "_")

In [19]:
weather["date"] = pd.to_datetime(weather["year"].astype(str) + "-" + weather["month"].astype(str) + "-01")

In [20]:
weather.drop(columns=["year", "month"], inplace=True)

In [21]:
print(weather.isnull().sum())

provorg    0
temp       0
wdsp       0
prcp       0
visib      0
date       0
dtype: int64

In [22]:
weather.interpolate(method="linear", inplace=True)
# Interpolate missing values for smooth temperature, wind speed, and visibility trends.

C:\Users\hp\AppData\Local\Temp\ipykernel_22984\2384642868.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  weather.interpolate(method="linear", inplace=True)

In [23]:
weather_monthly = weather.groupby(["date", "provorg"]).mean().reset_index()

In [24]:
df_merged = pollution_daily.merge(weather_monthly, on=["date", "provorg"], how="left")

In [25]:
df_merged.sort_values(by=["provorg", "date"], inplace=True)  # Ensure data is ordered
df_merged[["temp", "wdsp", "prcp", "visib"]] = df_merged.groupby("provorg")[["temp", "wdsp", "prcp", "visib"]].ffill()

In [26]:
df_merged[["temp", "wdsp", "prcp", "visib"]] = df_merged.groupby("provorg")[["temp", "wdsp", "prcp", "visib"]].bfill()

In [27]:
print(df_merged.isnull().sum())

date       0
provorg    0
avg_aqi    0
temp       0
wdsp       0
prcp       0
visib      0
dtype: int64

In [28]:
df_merged.to_csv("cleaned_pollution_weather.csv", index=False)

In [29]:
cleaned_pollution_weather=pd.read_csv("cleaned_pollution_weather.csv")
cleaned_pollution_weather.isna().sum()

date       0
provorg    0
avg_aqi    0
temp       0
wdsp       0
prcp       0
visib      0
dtype: int64

**Data Preprocessing for CEMS Dataset**

In [30]:
import pandas as pd

# Load datasets
df_allair = pd.read_stata("datasets/CEMS/allair_firmLNY_balanced.dta")
df_nox = pd.read_stata("datasets/CEMS/NOXnfirms.dta")
df_so2 = pd.read_stata("datasets/CEMS/SO2nfirms.dta")

In [31]:
print(df_allair.isnull().sum())
print(df_nox.isnull().sum())
print(df_so2.isnull().sum())

firm_name        0
pollutant        0
edate            0
time             0
concentration    0
provorg          0
dow              0
proven           0
dtype: int64
time         0
year         0
provorg      0
edate        0
nfirms       0
pollutant    0
dow          0
proven       0
provid       0
dtype: int64
time         0
year         0
provorg      0
edate        0
nfirms       0
pollutant    0
dow          0
proven       0
provid       0
dtype: int64

In [32]:
reference_date = pd.Timestamp("1960-01-01")

# Convert `edate` to actual date
df_allair["date"] = reference_date + pd.to_timedelta(df_allair["edate"], unit="D")
df_nox["date"] = reference_date + pd.to_timedelta(df_nox["edate"], unit="D")
df_so2["date"] = reference_date + pd.to_timedelta(df_so2["edate"], unit="D")

In [33]:
# Drop old `edate` column
df_allair.drop(columns=["edate"], inplace=True)
df_nox.drop(columns=["edate"], inplace=True)
df_so2.drop(columns=["edate"], inplace=True)

In [34]:
df_allair.head()

,firm_name,pollutant,time,concentration,provorg,dow,proven,date
0,安徽郎溪南方水泥有限公司,Particle,-12.0,7.762000,Anhui,3.0,HubeiNeighbor,2019-01-23
1,安徽郎溪南方水泥有限公司,Particle,-11.0,7.439913,Anhui,4.0,HubeiNeighbor,2019-01-24
2,安徽郎溪南方水泥有限公司,Particle,-10.0,7.495250,Anhui,5.0,HubeiNeighbor,2019-01-25
3,安徽郎溪南方水泥有限公司,Particle,-9.0,7.600667,Anhui,6.0,HubeiNeighbor,2019-01-26
4,安徽郎溪南方水泥有限公司,Particle,-8.0,7.589958,Anhui,0.0,HubeiNeighbor,2019-01-27

In [35]:
df_nox.head()

,time,year,provorg,nfirms,pollutant,dow,proven,provid,date
0,-21.0,2019.0,Anhui,8,NOX,1.0,HubeiNeighbor,1.0,2019-01-14
1,-20.0,2019.0,Anhui,13,NOX,2.0,HubeiNeighbor,1.0,2019-01-15
2,-19.0,2019.0,Anhui,13,NOX,3.0,HubeiNeighbor,1.0,2019-01-16
3,-18.0,2019.0,Anhui,13,NOX,4.0,HubeiNeighbor,1.0,2019-01-17
4,-17.0,2019.0,Anhui,13,NOX,5.0,HubeiNeighbor,1.0,2019-01-18

In [36]:
df_so2.head()

,time,year,provorg,nfirms,pollutant,dow,proven,provid,date
0,-21.0,2019.0,Anhui,12,SO2,1.0,HubeiNeighbor,1.0,2019-01-14
1,-20.0,2019.0,Anhui,17,SO2,2.0,HubeiNeighbor,1.0,2019-01-15
2,-19.0,2019.0,Anhui,17,SO2,3.0,HubeiNeighbor,1.0,2019-01-16
3,-18.0,2019.0,Anhui,18,SO2,4.0,HubeiNeighbor,1.0,2019-01-17
4,-17.0,2019.0,Anhui,19,SO2,5.0,HubeiNeighbor,1.0,2019-01-18

In [37]:
df_allair['concentration'].fillna(df_allair['concentration'].median(), inplace=True)
df_nox['nfirms'].fillna(df_nox['nfirms'].median(), inplace=True)
df_so2['nfirms'].fillna(df_so2['nfirms'].median(), inplace=True)

df_allair['pollutant'].fillna("Unknown", inplace=True)
df_nox['pollutant'].fillna("Unknown", inplace=True)
df_so2['pollutant'].fillna("Unknown", inplace=True)

In [38]:
print(df_allair.dtypes)
print(df_nox.dtypes)
print(df_so2.dtypes)

firm_name                object
pollutant                object
time                    float32
concentration           float64
provorg                  object
dow                     float32
proven                   object
date             datetime64[ns]
dtype: object
time                float32
year                float32
provorg              object
nfirms                int32
pollutant            object
dow                 float32
proven               object
provid              float32
date         datetime64[ns]
dtype: object
time                float32
year                float32
provorg              object
nfirms                int32
pollutant            object
dow                 float32
proven               object
provid              float32
date         datetime64[ns]
dtype: object

In [39]:
df_allair['concentration'] = df_allair['concentration'].astype(float)
df_nox['nfirms'] = df_nox['nfirms'].astype(int)
df_so2['nfirms'] = df_so2['nfirms'].astype(int)

In [40]:
print(df_allair.dtypes)
print(df_nox.dtypes)
print(df_so2.dtypes)

firm_name                object
pollutant                object
time                    float32
concentration           float64
provorg                  object
dow                     float32
proven                   object
date             datetime64[ns]
dtype: object
time                float32
year                float32
provorg              object
nfirms                int32
pollutant            object
dow                 float32
proven               object
provid              float32
date         datetime64[ns]
dtype: object
time                float32
year                float32
provorg              object
nfirms                int32
pollutant            object
dow                 float32
proven               object
provid              float32
date         datetime64[ns]
dtype: object

In [41]:
print(df_allair.duplicated().sum())
print(df_nox.duplicated().sum())
print(df_so2.duplicated().sum())

0
0
0

In [42]:
df_allair.columns = df_allair.columns.str.lower().str.replace(" ", "_")
df_nox.columns = df_nox.columns.str.lower().str.replace(" ", "_")
df_so2.columns = df_so2.columns.str.lower().str.replace(" ", "_")

In [43]:
from scipy import stats
import numpy as np
# Compute Z-scores
df_allair = df_allair[(np.abs(stats.zscore(df_allair['concentration'])) < 3)]
df_nox = df_nox[(np.abs(stats.zscore(df_nox['nfirms'])) < 3)]
df_so2 = df_so2[(np.abs(stats.zscore(df_so2['nfirms'])) < 3)]

In [44]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df_allair['concentration'] = scaler.fit_transform(df_allair[['concentration']])
df_nox['nfirms'] = scaler.fit_transform(df_nox[['nfirms']])
df_so2['nfirms'] = scaler.fit_transform(df_so2[['nfirms']])

In [45]:
df_allair.head()

,firm_name,pollutant,time,concentration,provorg,dow,proven,date
0,安徽郎溪南方水泥有限公司,Particle,-12.0,0.033801,Anhui,3.0,HubeiNeighbor,2019-01-23
1,安徽郎溪南方水泥有限公司,Particle,-11.0,0.032398,Anhui,4.0,HubeiNeighbor,2019-01-24
2,安徽郎溪南方水泥有限公司,Particle,-10.0,0.032639,Anhui,5.0,HubeiNeighbor,2019-01-25
3,安徽郎溪南方水泥有限公司,Particle,-9.0,0.033098,Anhui,6.0,HubeiNeighbor,2019-01-26
4,安徽郎溪南方水泥有限公司,Particle,-8.0,0.033052,Anhui,0.0,HubeiNeighbor,2019-01-27

In [46]:
df_nox.head()

,time,year,provorg,nfirms,pollutant,dow,proven,provid,date
0,-21.0,2019.0,Anhui,0.020460,NOX,1.0,HubeiNeighbor,1.0,2019-01-14
1,-20.0,2019.0,Anhui,0.033248,NOX,2.0,HubeiNeighbor,1.0,2019-01-15
2,-19.0,2019.0,Anhui,0.033248,NOX,3.0,HubeiNeighbor,1.0,2019-01-16
3,-18.0,2019.0,Anhui,0.033248,NOX,4.0,HubeiNeighbor,1.0,2019-01-17
4,-17.0,2019.0,Anhui,0.033248,NOX,5.0,HubeiNeighbor,1.0,2019-01-18

In [47]:
df_so2.head()

,time,year,provorg,nfirms,pollutant,dow,proven,provid,date
0,-21.0,2019.0,Anhui,0.031579,SO2,1.0,HubeiNeighbor,1.0,2019-01-14
1,-20.0,2019.0,Anhui,0.044737,SO2,2.0,HubeiNeighbor,1.0,2019-01-15
2,-19.0,2019.0,Anhui,0.044737,SO2,3.0,HubeiNeighbor,1.0,2019-01-16
3,-18.0,2019.0,Anhui,0.047368,SO2,4.0,HubeiNeighbor,1.0,2019-01-17
4,-17.0,2019.0,Anhui,0.050000,SO2,5.0,HubeiNeighbor,1.0,2019-01-18

In [48]:
df_combined = df_allair.merge(df_nox, on=["date", "provorg", "dow", "proven"], how="left")\
                       .merge(df_so2, on=["date", "provorg", "dow", "proven"], how="left")

# Save the final dataset
df_combined.to_csv("cleaned_cems.csv", index=False)

df_combined.head()

,firm_name,pollutant_x,time_x,concentration,provorg,dow,proven,date,time_y,year_x,nfirms_x,pollutant_y,provid_x,time,year_y,nfirms_y,pollutant,provid_y
0,安徽郎溪南方水泥有限公司,Particle,-12.0,0.033801,Anhui,3.0,HubeiNeighbor,2019-01-23,-12.0,2019.0,0.038363,NOX,1.0,-12.0,2019.0,0.057895,SO2,1.0
1,安徽郎溪南方水泥有限公司,Particle,-11.0,0.032398,Anhui,4.0,HubeiNeighbor,2019-01-24,-11.0,2019.0,0.035806,NOX,1.0,-11.0,2019.0,0.052632,SO2,1.0
2,安徽郎溪南方水泥有限公司,Particle,-10.0,0.032639,Anhui,5.0,HubeiNeighbor,2019-01-25,-10.0,2019.0,0.038363,NOX,1.0,-10.0,2019.0,0.055263,SO2,1.0
3,安徽郎溪南方水泥有限公司,Particle,-9.0,0.033098,Anhui,6.0,HubeiNeighbor,2019-01-26,-9.0,2019.0,0.035806,NOX,1.0,-9.0,2019.0,0.052632,SO2,1.0
4,安徽郎溪南方水泥有限公司,Particle,-8.0,0.033052,Anhui,0.0,HubeiNeighbor,2019-01-27,-8.0,2019.0,0.051151,NOX,1.0,-8.0,2019.0,0.068421,SO2,1.0

In [49]:
pd.read_csv('cleaned_cems.csv').isnull().sum()

firm_name            0
pollutant_x          0
time_x               0
concentration        0
provorg              0
dow                  0
proven               0
date                 0
time_y           13258
year_x           13258
nfirms_x         13258
pollutant_y      13258
provid_x         13258
time             13990
year_y           13990
nfirms_y         13990
pollutant        13990
provid_y         13990
dtype: int64

In [50]:
missing_percent = (df_combined.isnull().sum() / len(df_combined)) * 100
print(missing_percent)

firm_name        0.000000
pollutant_x      0.000000
time_x           0.000000
concentration    0.000000
provorg          0.000000
dow              0.000000
proven           0.000000
date             0.000000
time_y           7.211510
year_x           7.211510
nfirms_x         7.211510
pollutant_y      7.211510
provid_x         7.211510
time             7.609671
year_y           7.609671
nfirms_y         7.609671
pollutant        7.609671
provid_y         7.609671
dtype: float64

In [53]:
df_cleaned = df_combined.dropna()
df_cleaned.to_csv('cleaned_cems.csv', index=False)

In [54]:
pd.read_csv('cleaned_cems.csv').isnull().sum()

firm_name        0
pollutant_x      0
time_x           0
concentration    0
provorg          0
dow              0
proven           0
date             0
time_y           0
year_x           0
nfirms_x         0
pollutant_y      0
provid_x         0
time             0
year_y           0
nfirms_y         0
pollutant        0
provid_y         0
dtype: int64

In [55]:
num_rows = len(df_combined)
num_rows

183845

In [56]:
df_combined.columns

Index(['firm_name', 'pollutant_x', 'time_x', 'concentration', 'provorg', 'dow',
       'proven', 'date', 'time_y', 'year_x', 'nfirms_x', 'pollutant_y',
       'provid_x', 'time', 'year_y', 'nfirms_y', 'pollutant', 'provid_y'],
      dtype='object')